---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/books":
    get:
      summary: list books
      responses:
        '200':
          description: successful
    post:
      summary: create book
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: text
              required:
              - title
              - body
  "/api/v1/books/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show book
      responses:
        '200':
          description: successful
    patch:
      summary: update book
      responses:
        '200':
          description: successful
    put:
      summary: update book
      responses:
        '200':
          description: successful
    delete:
      summary: delete book
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
